loader:
  data_path: agent/data

embedding:
  cache_path: agent/cache/embeddings_cache.json

retriever:
  db_path: agent/chroma_db

database:
  dsn: "host=localhost user=postgres password=020203 dbname=golearn port=5432 sslmode=disable TimeZone=Asia/Shanghai"