name: env_langchain
channels:
  - defaults
dependencies:
  - aiodns=3.5.0=py310haa95532_0
  - aiohappyeyeballs=2.6.1=py310haa95532_0
  - aiosignal=1.4.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310h02ab6af_0
  - asttokens=3.0.0=py310haa95532_0
  - async-lru=2.0.4=py310haa95532_0
  - async-timeout=4.0.3=py310haa95532_0
  - babel=2.16.0=py310haa95532_0
  - beautifulsoup4=4.13.5=py310haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py310haa95532_0
  - blinker=1.9.0=py310haa95532_0
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.4=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - dataclasses-json=0.6.7=py310haa95532_0
  - debugpy=1.8.16=py310h885b0b7_0
  - decorator=5.2.1=py310haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - flask=3.1.2=py310haa95532_0
  - flask-sqlalchemy=3.1.1=py310haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - freetype=2.13.3=h0620614_0
  - graphite2=1.3.14=hd77b12b_1
  - greenlet=3.2.4=py310h885b0b7_0
  - h11=0.16.0=py310haa95532_0
  - harfbuzz=10.2.0=he2f9f60_1
  - httpcore=1.0.9=py310haa95532_0
  - httpx=0.28.1=py310haa95532_0
  - icu=73.1=h6c2663c_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=py310haa95532_0
  - ipython=8.30.0=py310haa95532_0
  - ipywidgets=8.1.5=py310haa95532_0
  - itsdangerous=2.2.0=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - jiter=0.6.1=py310hefb1915_0
  - jpeg=9f=ha349fce_0
  - json5=0.9.25=py310haa95532_0
  - jsonpatch=1.33=py310haa95532_1
  - jsonpointer=3.0.0=py310haa95532_0
  - jsonschema=4.25.0=py310haa95532_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter=1.1.1=py310haa95532_0
  - jupyter-lsp=2.2.5=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - jupyter_events=0.12.0=py310haa95532_0
  - jupyter_server=2.16.0=py310haa95532_0
  - jupyter_server_terminals=0.5.3=py310haa95532_0
  - jupyterlab=4.4.7=py310haa95532_0
  - jupyterlab_pygments=0.3.0=py310haa95532_0
  - jupyterlab_server=2.27.3=py310haa95532_0
  - jupyterlab_widgets=3.0.15=py310haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.20=h83e8143_0
  - libuv=1.48.0=h827c3e9_0
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.7=py310haa95532_0
  - mistune=3.1.2=py310haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.4.0=py310h827c3e9_3
  - mkl_fft=1.3.11=py310h5810407_1
  - mkl_random=1.2.8=py310h8683371_1
  - mypy_extensions=1.0.0=py310haa95532_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - nbclient=0.10.2=py310haa95532_0
  - nbconvert=7.16.6=py310haa95532_0
  - nbconvert-core=7.16.6=py310haa95532_0
  - nbconvert-pandoc=7.16.6=py310haa95532_0
  - nbformat=5.10.4=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - notebook=7.4.5=py310haa95532_0
  - notebook-shim=0.2.4=py310haa95532_0
  - openai=1.109.1=py310haa95532_0
  - openssl=3.0.18=h543e019_0
  - overrides=7.4.0=py310haa95532_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.1=py310haa95532_0
  - parso=0.8.4=py310haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.3.7=py310haa95532_0
  - prometheus_client=0.21.1=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=7.0.0=py310h02ab6af_0
  - pure_eval=0.2.3=py310haa95532_0
  - pycares=4.10.0=py310he29e43d_0
  - pycparser=2.23=py310haa95532_0
  - pydantic-core=2.33.2=py310h215eeae_0
  - pygments=2.19.1=py310haa95532_0
  - pymysql=1.1.1=py310haa95532_0
  - pyqt=6.9.1=py310h12ec796_0
  - pyqt6-sip=13.10.2=py310h630b2a1_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-fastjsonschema=2.20.0=py310haa95532_0
  - python-json-logger=3.2.1=py310haa95532_0
  - pywin32=311=py310h885b0b7_0
  - pywinpty=2.0.15=py310h72d21ff_0
  - pyzmq=27.1.0=py310h7149c55_0
  - qtbase=6.9.2=hd965823_0
  - qtconsole=5.6.1=py310haa95532_1
  - qtdeclarative=6.9.2=h88b4c33_0
  - qtpy=2.4.3=py310haa95532_0
  - qtsvg=6.9.2=h30ace32_0
  - qttools=6.9.2=h7e7b719_0
  - qtwebchannel=6.9.2=heb02b0b_0
  - qtwebsockets=6.9.2=heb02b0b_0
  - referencing=0.30.2=py310haa95532_0
  - regex=2024.11.6=py310h827c3e9_0
  - requests=2.32.5=py310haa95532_0
  - requests-toolbelt=1.0.0=py310haa95532_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.22.3=py310h636fa0f_0
  - send2trash=1.8.2=py310haa95532_1
  - sip=6.12.0=py310h706e071_0
  - six=1.17.0=py310haa95532_0
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py310haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - terminado=0.18.1=py310haa95532_0
  - tinycss2=1.4.0=py310haa95532_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py310haa95532_0
  - tornado=6.5.1=py310h827c3e9_0
  - tqdm=4.67.1=py310h9909e9c_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing-inspection=0.4.2=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - typing_inspect=0.9.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py310haa95532_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=1.8.0=py310haa95532_0
  - werkzeug=3.1.3=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - widgetsnbextension=4.0.13=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - winloop=0.2.2=py310h913537a_0
  - winpty=0.4.3=4
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohttp==3.13.2
      - aioprometheus==23.12.0
      - aiosqlite==0.21.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==4.2.2
      - altex==0.2.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anthropic==0.72.0
      - antlr4-python3-runtime==4.9.3
      - anyascii==0.3.3
      - anyio==4.11.0
      - argbind==0.3.9
      - argcomplete==3.6.3
      - asgiref==3.10.0
      - attrdict==2.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - av==16.0.1
      - backoff==2.2.1
      - bcrypt==5.0.0
      - black==25.9.0
      - blis==1.3.0
      - blobfile==3.1.0
      - boto3==1.40.66
      - botocore==1.40.66
      - brotli==1.1.0
      - build==1.3.0
      - cachetools==5.5.2
      - catalogue==2.0.10
      - cbor==1.0.0
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - chroma-hnswlib==0.7.3
      - chromadb==1.3.4
      - click==8.1.8
      - cloudpathlib==0.23.0
      - cloudpickle==3.1.2
      - cn2an==0.5.23
      - coloredlogs==15.0.1
      - confection==0.1.5
      - conformer==0.3.2
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.3
      - csvw==3.7.0
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cycler==0.12.1
      - cymem==2.0.11
      - datamodel-code-generator==0.35.0
      - datasets==4.3.0
      - dateparser==1.1.8
      - deepdiff==8.6.1
      - deprecated==1.3.1
      - deprecation==2.1.0
      - diffusers==0.35.2
      - dill==0.4.0
      - distance==0.1.3
      - dlinfo==2.0.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - durationpy==0.10
      - ecdsa==0.19.1
      - editdistance==0.8.1
      - einops==0.8.1
      - einx==0.3.0
      - emoji==2.15.0
      - encodec==0.1.1
      - entrypoints==0.4
      - espeakng-loader==0.2.4
      - et-xmlfile==2.0.0
      - eva-decord==0.6.1
      - exceptiongroup==1.3.0
      - faiss-cpu==1.12.0
      - faker==37.12.0
      - fastapi==0.115.2
      - favicon==0.7.0
      - ffmpy==0.6.4
      - filelock==3.19.1
      - filetype==1.2.0
      - fire==0.7.1
      - flask-cors==6.0.1
      - flatbuffers==25.9.23
      - flatten-dict==0.4.2
      - fonttools==4.60.1
      - frozendict==2.4.6
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - fugashi==1.5.2
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - g2p-en==2.1.0
      - gdown==5.2.0
      - genson==1.3.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.9.0
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.1
      - google-cloud-core==2.5.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gradio==5.49.1
      - gradio-client==1.13.3
      - groovy==0.1.2
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - gruut==2.4.0
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - h2==4.3.0
      - hf-xet==1.2.0
      - hpack==4.1.0
      - htbuilder==0.9.0
      - html5lib==1.1
      - httplib2==0.31.0
      - httptools==0.6.4
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - hyperframe==6.1.0
      - hyperpyyaml==1.2.2
      - idna==3.11
      - ijson==3.4.0.post0
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - inscriptis==2.6.0
      - iopath==0.1.10
      - ir-datasets==0.5.11
      - isodate==0.7.2
      - isort==6.1.0
      - jaconv==0.4.0
      - jamo==0.4.1
      - jieba==0.42.1
      - jj-pytorchvideo==0.1.5
      - jmespath==0.10.0
      - joblib==1.5.2
      - jq==1.10.0
      - jsonlines==1.2.0
      - jsonpath-ng==1.7.0
      - jsonpath-python==1.0.6
      - jsonpickle==4.1.1
      - julius==0.2.7
      - kaldifst==1.7.17
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - kubernetes==29.0.0
      - langchain==1.1.0
      - langchain-chroma==1.0.0
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.1.0
      - langchain-experimental==0.4.0
      - langchain-google-genai==3.2.0
      - langchain-huggingface==1.1.0
      - langchain-openai==1.1.0
      - langchain-tavily==0.2.13
      - langchain-text-splitters==1.0.0
      - langchainhub==0.1.14
      - langcodes==3.5.0
      - langdetect==1.0.9
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.0
      - langgraph-checkpoint-postgres==3.0.1
      - langgraph-checkpoint-redis==0.2.1
      - langgraph-checkpoint-sqlite==3.0.0
      - langgraph-prebuilt==1.0.5
      - langgraph-sdk==0.2.9
      - langserve==0.3.3
      - langsmith==0.4.47
      - language-data==1.3.0
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - loguru==0.7.3
      - loralib==0.1.2
      - lxml==6.0.2
      - lz4==4.4.5
      - marisa-trie==1.3.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markdownify==1.2.0
      - markdownlit==0.0.7
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mecab-python3==1.0.10
      - memoization==0.4.0
      - misaki==0.9.4
      - ml-dtypes==0.5.4
      - mmh3==5.2.0
      - modelscope==1.31.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - munch==4.0.0
      - murmurhash==1.0.13
      - mypy-extensions==1.1.0
      - natsort==8.4.0
      - networks==0.3.7
      - networkx==3.3
      - nltk==3.8.1
      - num2words==0.5.14
      - numba==0.62.1
      - numexpr==2.13.1
      - numpy==2.2.6
      - nvidia-ml-py==13.580.82
      - oauthlib==3.3.1
      - olefile==0.47
      - ollama==0.6.0
      - omegaconf==2.3.0
      - onnxruntime==1.23.0
      - opencv-python==4.10.0.84
      - openpyxl==3.1.4
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-grpc==1.37.0
      - opentelemetry-instrumentation==0.58b0
      - opentelemetry-instrumentation-asgi==0.58b0
      - opentelemetry-instrumentation-fastapi==0.58b0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - opentelemetry-util-http==0.58b0
      - ordered-set==4.1.0
      - orderly-set==5.5.0
      - orjson==3.11.4
      - ormsgpack==1.11.0
      - packaging==23.2
      - pandas==2.3.3
      - parameterized==0.9.0
      - pathlib==1.0.1
      - pathspec==0.12.1
      - pillow==11.3.0
      - pip==25.3
      - ply==3.11
      - pooch==1.8.2
      - portalocker==3.2.0
      - posthog==5.4.0
      - preshed==3.0.10
      - proces==0.1.7
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psycopg==3.3.0
      - psycopg-binary==3.3.0
      - psycopg-pool==3.3.0
      - pulsar-client==3.8.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase16384==0.3.8
      - pybase64==1.4.2
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.10
      - pydantic-settings==2.11.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyjwt==2.8.0
      - pykakasi==2.3.0
      - pyloudnorm==0.1.1
      - pymdown-extensions==10.16.1
      - pymupdf==1.23.26
      - pymupdfb==1.23.22
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pypdf==6.1.1
      - pypika==0.48.9
      - pypinyin==0.55.0
      - pypinyin-dict==0.9.0
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-crfsuite==0.9.11
      - python-decouple==3.8
      - python-docx==1.1.2
      - python-dotenv==1.2.1
      - python-iso639==2025.2.18
      - python-jose==3.5.0
      - python-magic==0.4.27
      - python-magic-bin==0.4.14
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - python-ulid==3.1.0
      - pytokens==0.3.0
      - pytorch-wpe==0.0.1
      - pytz==2025.2
      - pyworld==0.3.5
      - pyyaml==6.0.3
      - quantile-python==1.1
      - qwen-vl-utils==0.0.14
      - randomname==0.2.1
      - rank-bm25==0.2.2
      - rapidfuzz==3.14.1
      - rapidocr-onnxruntime==1.3.25
      - rdflib==7.4.0
      - redis==6.4.0
      - redisvl==0.12.1
      - requests-oauthlib==2.0.0
      - rfc3986==1.5.0
      - rich==13.9.4
      - rsa==4.9.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.14
      - ruff==0.14.3
      - s3transfer==0.14.0
      - safehttpx==0.1.7
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - setproctitle==1.3.7
      - setuptools==80.9.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - silero-vad==6.1.0
      - simplejson==3.20.2
      - smart-open==7.4.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.8.7
      - spacy-curated-transformers==0.3.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.44
      - sqlite-vec==0.1.6
      - srsly==2.5.1
      - sse-starlette==1.8.2
      - st-annotated-text==4.0.2
      - starlette==0.40.0
      - streamlit==1.34.0
      - streamlit-aggrid==1.0.5
      - streamlit-antd-components==0.3.1
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==1.0.2
      - streamlit-chatbox==1.1.12.post4
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.4.2
      - streamlit-faker==0.0.4
      - streamlit-feedback==0.1.4
      - streamlit-image-coordinates==0.1.9
      - streamlit-keyup==0.3.0
      - streamlit-modal==0.1.0
      - streamlit-option-menu==0.3.12
      - streamlit-paste-button==0.1.2
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==2.5.5
      - strsimpy==0.2.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.2.1
      - tenacity==8.2.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.2.0
      - thinc==8.3.7
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - toolz==1.1.0
      - torch==2.6.0+cu124
      - torch-complex==0.4.4
      - torchaudio==2.6.0+cu124
      - torchdiffeq==0.2.5
      - torchmetrics==1.8.2
      - torchvision==0.21.0+cu124
      - transformers==4.57.1
      - transformers-stream-generator==0.0.5
      - trec-car-tools==2.6
      - typeguard==4.4.4
      - typer==0.19.2
      - types-requests==2.32.4.20250913
      - tzdata==2025.2
      - tzlocal==5.3.1
      - umap-learn==0.5.9.post2
      - unidic-lite==1.0.8
      - unlzw3==0.2.3
      - unstructured==0.11.8
      - unstructured-client==0.25.9
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uv==0.9.7
      - uvicorn==0.37.0
      - validators==0.35.0
      - vector-quantize-pytorch==1.17.3
      - verovio==5.6.0
      - vocos==0.1.0
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - wasabi==1.1.3
      - watchdog==6.0.0
      - watchfiles==1.1.0
      - weasel==0.4.1
      - websockets==15.0.1
      - wetext==0.1.0
      - win32-setctime==1.2.0
      - wrapt==1.17.3
      - x-transformers==2.11.7
      - xllamacpp==0.2.4
      - xoscar==0.8.0
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.22.0
      - zipp==3.23.0
      - zlib-state==0.1.10
      - zstandard==0.23.0
prefix: D:\anaconda\envs\env_langchain
